name: weixin
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 # 更新为最新版本，例如 actions/checkout@v3
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2 # 更新为最新版本，例如 actions/setup-python@v3
        with:
          python-version: 3.9.1
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          python3 main.py
